191118/django_subway/crud/urls.py
from django.urls import path
from . import views 

app_name = "crud"
urlpatterns = [
    path('new/', views.new, name='new'), #crud/new/
    # path('create/', views.create, name='create'), #crud/create/
    path('', views.index, name='index'), #crud/
    # crud/pk/article/ detail page
    path('<int:pk>/detail/', views.detail, name='detail'), # 해당 url로 가면 views.detail 실행하겠다!
    # crud/pk/update/ 수정 페이지
    path('<int:pk>/update/', views.update, name='update'),
    # crud/pk/revise/ 최종 업데이트
    # path('<int:pk>/revise/', views.revise, name='revise'),
    # crud/pk/delete/ 삭제하기
    path('<int:pk>/delete/', views.delete, name='delete'),
]

191118/django_subway/crud/models.py
from django.db import models
   
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length =50) #기사 제목 / 문자열
    content = models.TextField() #기사 내용
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True) # editable option => False 
   
    def __str__(self):
        return f'{self.id} : {self.title}'

class Comment(models.Model):
    comment = models.CharField(max_length=200)
    # ForeignKey(어떤 테이블을 참조할지, 그 테이블이 삭제될 때 어떻게 할지)
    # models.CASCADE : 부모 테이블 삭제시 같이 삭제하는 옵션
    # models.PROTECT : 부모 테이블이 삭제될 때 오류 발생
    # models.SET_NULL : 삭제되었을 때, 부모 참조 값을 NULL값으로 채움. 단, NOT NULL 옵션인 경우에는 불가능
    # models.SET() : 특정 함수를 호출
    # models.DO_NOTHING : 아무것도 안함
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

191118/django_subway/crud/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.


def new(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')      
        #db저장
        article=Article()
        article.title = title
        article.content = content
        article.save()
        return render(request, "crud/created.html")
    else:
        return render(request, "crud/new.html")

# def create(request):
#     title = request.POST.get('title')
#     content = request.POST.get('content')      
#     #db저장
#     article=Article()
#     article.title = title
#     article.content = content
#     article.save()
#     return render(request, "crud/created.html")

def index(request) : 
    # 1번째 파이썬에서 정렬하는 방법
    # articles = Article.objects.all()[::-1] # 역순으로 저장
    
    # 2번째 불러올 때 정렬시키는 법
    articles = Article.objects.order_by('-id')
    
    context = {
        "articles" : articles
    }
    return render(request, 'crud/index.html', context)

def detail(request, pk):
    # (pk=pk)가 (id__exact=pk)와 같음
    article = Article.objects.get(pk=pk)
    
    context = {
        "article" : article
    }
    return render(request, 'crud/detail.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method=="POST":
        article = Article.objects.get(pk=pk)
        title = request.POST.get('title')
        content = request.POST.get('content')
        print(content)
        article.title = title
        article.content = content
        article.save()
        return redirect('crud:detail', pk) # redirect import
    
    else:
        context = {
            "article": article
        }
        return render(request, 'crud/update.html', context)

# def revise(request, pk):
#     article = Article.objects.get(pk=pk)
#     title = request.POST.get('title')
#     content = request.POST.get('content')
#     print(content)
#     article.title = title
#     article.content = content
#     article.save()
#     return redirect(f'crud:detail') # redirect import

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        article.delete()
        return redirect('crud:index')
    else:
        return redirect('crud:detail', article.id)

191118/django_subway/crud/templates/crud/created.html
{%extends 'base.html'%}
{%block title%}
Success Page
{%endblock%}
{%block body%}
article 작성이 완료되었습니다.
{%endblock%}

191118/django_subway/crud/templates/crud/detail.html
{% extends 'base.html' %}
{% block body %}
	제목 : {{ article.title }} <br>
	내용 : {{ article.content }} <br>
	<a href="{% url 'crud:update' article.id %}">수정하기</a>
	<form action="{% url 'crud:delete' article.id %}" method="post">
		{% csrf_token %}
		<input type='submit' value="삭제하기">
	</form>
	
{% endblock %}

191118/django_subway/crud/templates/crud/index.html
{% extends 'base.html' %}

{% block body %}
<h1> Article LIst </h1>
<ul>
    {% for art in articles %}
    <li> <a href="{% url 'crud:detail' art.id %}"> {{art.title}} </a></li>
    {% endfor %}
</ul>
{% endblock %}

191118/django_subway/crud/templates/crud/new.html
{%extends 'base.html'%}
{%block title%}
New
{%endblock%}

{%block body%}
<!-- 작성할 폼 -->
<form action="{% url 'crud:new' %}" method='POST'>
    {%csrf_token%}
    <label for="title">Title</label>
    <input type="text" name="title" id="title"> <br>
    <label for="content">Contents</label>
    <textarea name="content" cols="30" rows="5" id="content"></textarea>
    <!-- 30글자 5줄 -->
    <input type='submit'>
</form>
{%endblock%}

191118/django_subway/crud/templates/crud/update.html
{% extends 'base.html' %}
{% block body %}
    <form action="{% url 'crud:update' article.id %}" method='POST'>
        {% csrf_token %}
        <input type="text" name="title" value="{{ article.title }}"><br>
        <textarea name="content" cols="30" rows="10">{{article.content}}</textarea> <br>
        <input type="submit">
    </form>
{% endblock %}