191119/django_practice/board/urls.py
from django.urls import path
from . import views 

app_name = "board"
urlpatterns = [
    path('new/', views.new, name="new"),
    # path('/', views.index, name="index"),
    path('', views.index, name="index"),
    path('<int:pk>/detail/', views.detail, name="detail"),
    path('<int:pk>/snew/', views.snew, name="snew"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:pk>/sdelete/', views.sdelete, name="sdelete"),
    path('<int:pk>/vote/', views.vote, name="vote")

]

191119/django_practice/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
]

191119/django_practice/board/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Choice(models.Model):
    survey = models.CharField(max_length=50)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    votes = models.IntegerField(default=0)

191119/django_practice/board/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice

# Create your views here.
def new(request):
    if request.method=="POST":
        question = request.POST.get("question")
        q = Question()
        q.question = question
        q.save()
        return redirect("board:index")       
    else:
        return render(request, "board/new.html")

def index(request):
    questions = Question.objects.all()
    context = {
        "questions" : questions
    }
    return render(request, "board/index.html", context)

def detail(request, pk):
    question = Question.objects.get(id=pk)
    choices = question.choice_set.all()
    context = {
        "question" : question,
        "choices" : choices
    }
    return render(request, "board/detail.html", context)

def snew(request, pk):
    question = Question.objects.get(id=pk)
    survey = request.POST.get("survey")
    choice = Choice(survey = survey, question = question)
    choice.save()
    return redirect("board:detail", pk)

def delete(request, pk):
    question = Question.objects.get(id=pk)
    question.delete()
    return redirect("board:index")

def update(request, pk):
    choice = Choice.objects.get(id=pk)
    if request.method == "POST":
        survey = request.POST.get("survey")
        choice.survey = survey
        choice.save()
        return redirect("board:detail", choice.question_id)
    else:
        context = {
            "choice" : choice
        }
        return render(request, "board/update.html", context)

def sdelete(request, pk):
    choice = Choice.objects.get(id=pk)
    choice.delete()
    return redirect("board:detail", choice.question_id)

def vote(request, pk):
    choice = Choice.objects.get(id=pk)
    if request.method == "POST":
        choice.votes += 1
        choice.save()
        return redirect("board:detail", choice.question_id)
    

191119/django_practice/board/templates/board/detail.html
{% extends 'base.html' %}
{% block body %}
{% csrf_token %}
<h3> {{question.question}} </h3>
<form action="{% url 'board:delete' question.id %}" method='POST'>
        {% csrf_token %}
    <input type='submit' value='삭제하기'>
</form>
<br>

<ul>
{% for choice in choices %}
<li>{{choice.survey}} &nbsp; [{{choice.votes}}]
<form action="{% url 'board:vote' choice.id %}" method='POST'>
    {% csrf_token %}
    <a href="#" onclick="this.parentNode.submit()">투표하기</a>
    <a href="{% url 'board:update' choice.id %}">수정하기</a>
</form>
</li>
{% endfor %}

</ul>
<br>

<form action="{% url 'board:snew' question.id %}" method='POST'>
    {% csrf_token %}
    <input type="text" name="survey" id="survey">
    <input type='submit' value='항목 추가'>
</form>

{% endblock %}

191119/django_practice/board/templates/board/index.html
{% extends 'base.html' %}
{% block body %}

{% csrf_token %}

<h3> 질문 LIST </h3>
<ul>
{% for q in questions %}
<li> <a href="{% url 'board:detail' q.id %}"> {{q.question}} </a> </li>
{% endfor %}
</ul>


{% endblock %}

191119/django_practice/board/templates/board/new.html
{% extends 'base.html' %}
{% block body %}

<form action="{% url 'board:new' %}" method='POST'>
    {% csrf_token %}
    <input type="text" name="question" id="question">
    <input type='submit' value='질문 올리기'>
</form>

{% endblock %}

191119/django_practice/board/templates/board/update.html
{% extends 'base.html' %}
{% block body %}

<form action="{% url 'board:update' choice.id %}" method='POST'>
    {% csrf_token %}
    <input type="text" name="survey" id="survey" value="{{choice.survey}}">
    <input type='submit' value='수정하기'>
</form>
<br>

<form action="{% url 'board:sdelete' choice.id %}" method='POST'>
    {% csrf_token %}
    <input type='submit' value='삭제하기'>
</form>

{% endblock %}