191118/django_subway/subway/urls.py
from django.urls import path
from . import views

app_name = "subway" # path 이름이 겹쳐서 name space를 사용할 때 문제가 생길 경우를 대비해 appname을 설정해 줄 수 있다. 
urlpatterns = [
    # name을 설정하면 url 관리가 수월하다.
    # {% url 'app_name:설정name' %} 방식으로 사용
    # url이 바뀌어도 일일이 찾아서 바꿀 필요가 없다.
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),
    # {% url 'app_name:설정name' 넘길데이터1 넘길데이터2 %}
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    # path('<int:pk>/change/', views.change, name='change'),
    path('<int:pk>/delete/', views.delete, name='delete')
]

191118/django_subway/subway/models.py
from django.db import models

# Create your models here.
class Subway(models.Model):
    name = models.CharField(max_length=15)
    address = models.TextField()
    phone = models.TextField()
    menu = models.TextField()
    bread = models.TextField()
    vegetable = models.TextField()
    sauce = models.TextField()
    drink = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return f'{self.name} : {self.menu}'

191118/django_subway/subway/views.py
from django.shortcuts import render, redirect
from .models import Subway

# Create your views here.
def index(request):
    orders = Subway.objects.all()
    context = {
        'orders' : orders
    }
    return render(request, 'subway/index.html', context)

def new(request):
    if request.method=="POST":
        name = request.POST.get('name')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        menu = request.POST.get('menu')
        bread = request.POST.get('bread')
        vegetable = request.POST.get('vegetable')
        sauce = request.POST.get('sauce')
        drink = request.POST.get('drink')

        subway = Subway()

        subway.name = name
        subway.address = address
        subway.phone = phone
        subway.menu = menu
        subway.bread = bread
        subway.vegetable = vegetable
        subway.sauce = sauce
        subway.drink = drink

        subway.save()

        return redirect('subway:index')

    else:
        menu=['에그마요', '이탈리안 비엠티', '터키 베이컨 아보카도']
        bread = ['화이트', '하티', '파마산오레가노', '위트', '허니오트', '플랫']
        vegetable = ['토마토', '오이', '할라피뇨', '양상추']
        sauce = ['레드식초', '샤우젼아일랜드', '스위트칠리', '허니머스타드']
        drink = ['콜라', '사이다', '환타', '스프라이트']
        context= {
            'menu' : menu,
            'bread' : bread,
            'vegetable' : vegetable,
            'sauce' : sauce,
            'drink' : drink
        }
        return render(request, 'subway/new.html', context)

# def create(request):
#     name = request.POST.get('name')
#     address = request.POST.get('address')
#     phone = request.POST.get('phone')
#     menu = request.POST.get('menu')
#     bread = request.POST.get('bread')
#     vegetable = request.POST.get('vegetable')
#     sauce = request.POST.get('sauce')
#     drink = request.POST.get('drink')

#     subway = Subway()

#     subway.name = name
#     subway.address = address
#     subway.phone = phone
#     subway.menu = menu
#     subway.bread = bread
#     subway.vegetable = vegetable
#     subway.sauce = sauce
#     subway.drink = drink

#     subway.save()

#     return redirect('subway:index')

def detail(request, pk):
    order = Subway.objects.get(id=pk)
    context = {
        'order' : order
    }
    return render(request, 'subway/detail.html', context)

def update(request, pk):
    if request.method=="POST":
        order = Subway.objects.get(id=pk)

        menu = request.POST.get('menu')
        bread = request.POST.get('bread')
        vegetable = request.POST.get('vegetable')
        sauce = request.POST.get('sauce')
        drink = request.POST.get('drink')

        print(menu)

        order.menu = menu
        order.bread = bread
        order.vegetable = vegetable
        order.sauce = sauce
        order.drink = drink

        order.save()
        return redirect('subway:index')
    
    else:
        order = Subway.objects.get(id=pk)
        menu=['에그마요', '이탈리안 비엠티', '터키 베이컨 아보카도']
        bread = ['화이트', '하티', '파마산오레가노', '위트', '허니오트', '플랫']
        vegetable = ['토마토', '오이', '할라피뇨', '양상추']
        sauce = ['레드식초', '샤우젼아일랜드', '스위트칠리', '허니머스타드']
        drink = ['콜라', '사이다', '환타', '스프라이트']
        context= {
            'menu' : menu,
            'bread' : bread,
            'vegetable' : vegetable,
            'sauce' : sauce,
            'drink' : drink,
            'order': order
        }
        return render(request, 'subway/update.html', context)

# def change(request, pk):
#     order = Subway.objects.get(id=pk)

#     menu = request.POST.get('menu')
#     bread = request.POST.get('bread')
#     vegetable = request.POST.get('vegetable')
#     sauce = request.POST.get('sauce')
#     drink = request.POST.get('drink')

#     print(menu)

#     order.menu = menu
#     order.bread = bread
#     order.vegetable = vegetable
#     order.sauce = sauce
#     order.drink = drink

#     order.save()
#     return redirect('subway:index')

def delete(request, pk):
    order = Subway.objects.get(id=pk)

    if request.method=="POST":
        order.delete()

        return redirect('subway:index')
    
    else:
        return redirect('subway:detail', order.id)

191118/django_subway/subway/templates/subway/detail.html
{% extends 'base.html' %}
{% block body %}
    주문자명 : {{order.name}} <br>
    주소 : {{order.address}} <br>
    전화번호 : {{order.phone}} <br>
    주문메뉴 : {{order.menu}} <br>
    빵 : {{order.bread}} <br>
    야채 : {{order.vegetable}} <br>
    소스 : {{order.sacue}} <br>
    음료 : {{order.drink}} <br>
    주문일자 : {{order.created_at}} <br>
    주문정보 수정일자 : {{order.updated_at}} <br>
    <a href="{% url 'subway:update' order.id %}"> 수정하기 </a>
    <form action="{% url 'subway:delete' order.id %}" method='POST'>
        {% csrf_token %}
        <input type='submit' value="삭제하기">
    </form>
{% endblock %}

191118/django_subway/subway/templates/subway/index.html
{% extends 'base.html' %}
{% block body %}
    <ul>
        {% for order in orders %} <!--넘길 값은 띄어쓰기 하고 써주면 됨. 만약에 2개를 넘긴다면 한 칸 더 띄우고 추가 -->
        <li> <a href="{% url 'subway:detail' order.id %}">{{order}} </a></li>
        {% endfor %}
    </ul>
    
{% endblock %}

191118/django_subway/subway/templates/subway/new.html
{% extends 'base.html' %}
{% block body %}

<form action="{% url 'subway:new' %}" method="POST">
    {% csrf_token %}
    <!-- hidden 값으로 token 전달 -->
    <h3>주문해주세요.</h3>
    <label type="uname">Name</label>
    <input type="text" name="name" id="uname" placeholder="성함을 입력하세요."> <br>
    <label type="address">Address</label>
    <input type="text" name="address" id="address" placeholder="주소를 입력하세요."> <br>
    <label type="phone">Phone</label>
    <input type="text" name="phone" id="phone" placeholder='XXX-XXXX-XXXX'> <br>
<hr>
    <h3>1. 메뉴 선택</h3>
    {%for m in menu%}
    <input type="radio" name="menu" id="{{m}}" value="{{m}}">
    <label type="{{m}}">{{m}}</label><br>
    {%endfor%}

<hr>
    <h3>2. 빵 선택</h3>
    <input list="breads" name="bread">
    <datalist id="breads">
    {%for b in bread%}
        <option value="{{b}}">
    {%endfor%}
    </datalist>

<hr>
    <h3>3. 야채 선택</h3>
    {%for v in vegetable%}
    <input type="checkbox" name="vegetable" id="{{v}}" value="{{v}}">
    <label type="{{v}}">{{v}}</label><br>
    {%endfor%}

<hr>
    <h3>4. 소스 선택</h3>
    {%for s in sauce%}
    <input type="checkbox" name="sauce" id="{{s}}" value="{{s}}">
    <label type="{{s}}">{{s}}</label><br>
    {%endfor%}

<hr>
    <h3>5. 음료 선택</h3>
    <input list="drink" name="drink">
    <datalist id="drink">
    {%for d in drink%}
        <option value="{{d}}">
    {%endfor%}
    </datalist>
    
    <input type="submit" value="order">
</form>

{% endblock %}

191118/django_subway/subway/templates/subway/update.html
{% extends 'base.html' %}
{% block body %}

<form action="{% url 'subway:update' order.id %}" method="POST">
    {% csrf_token %}
    <!-- hidden 값으로 token 전달 -->
    <h3>주문 정보를 수정해주세요.</h3>
    주문자명 : {{order.name}} <br>
    주소 : {{order.address}} <br>
    전화번호 : {{order.phone}} <br>
<hr>
    <h3>1. 메뉴 선택</h3>
    {%for m in menu%}
    <input type="radio" name="menu" id="{{m}}" value="{{m}}">
    <label type="{{m}}">{{m}}</label><br>
    {%endfor%}

<hr>
    <h3>2. 빵 선택</h3>
    <input list="breads" name="bread">
    <datalist id="breads">
    {%for b in bread%}
        <option value="{{b}}">
    {%endfor%}
    </datalist>

<hr>
    <h3>3. 야채 선택</h3>
    {%for v in vegetable%}
    <input type="checkbox" name="vegetable" id="{{v}}" value="{{v}}">
    <label type="{{v}}">{{v}}</label><br>
    {%endfor%}

<hr>
    <h3>4. 소스 선택</h3>
    {%for s in sauce%}
    <input type="checkbox" name="sauce" id="{{s}}" value="{{s}}">
    <label type="{{s}}">{{s}}</label><br>
    {%endfor%}

<hr>
    <h3>5. 음료 선택</h3>
    <input list="drink" name="drink">
    <datalist id="drink">
    {%for d in drink%}
        <option value="{{d}}">
    {%endfor%}
    </datalist>
    
    <input type="submit" value="update">
</form>

{% endblock %}